apiVersion: linstor.linbit.com/v1alpha1
kind: LinstorNodeSet
metadata:
  name: {{ template "linstor-operator.fullname" . }}-ns
spec:
  drbdKernelModuleInjectionMode: {{ .Values.operator.nodeSet.spec.drbdKernelModuleInjectionMode }}
  drbdRepoCred: {{ .Values.drbdRepoCred }}
  linstorSatImage: {{ .Values.operator.nodeSet.spec.linstorSatImage }}
  linstorSatVersion: {{ .Values.operator.nodeSet.spec.linstorSatVersion }}
  linstorKernelModImage: {{ .Values.operator.nodeSet.spec.linstorKernelModImage }}
  linstorKernelModVersion: {{ .Values.operator.nodeSet.spec.linstorKernelModVersion }}
  storagePools:
    lvmPools:
    - name: {{ .Values.operator.nodeSet.spec.lvmPoolName }}
      volumeGroup: {{ .Values.operator.nodeSet.spec.lvmPoolVgName }}
    lvmThinPools:
    - name: {{ .Values.operator.nodeSet.spec.lvmThinPoolName }}
      volumeGroup: {{ .Values.operator.nodeSet.spec.lvmThinPoolVgName }}
      thinVolume: {{ .Values.operator.nodeSet.spec.lvmThinPoolLvName }}
