apiVersion: linstor.linbit.com/v1alpha1
kind: LinstorControllerSet
metadata:
  name: {{ template "linstor-operator.fullname" . }}-cs
spec:
  # etcdURL: etcd://{{ template "linstor-operator.name" . }}:2379
  # etcdURL: etcd://{{ template "linstor-operator.name" . }}:2379
  etcdURL: etcd://{{ .Release.Name }}-etcd:2379  # TODO: Fix
  # etcdURL: etcd://{{ .Release.Name }}.{{ .Release.Namespace }}.{{ .Values.etcd.service.dnsBase }}:{{ .Values.etcd.service.port }}
  drbdRepoCred: {{ .Values.repoCreds }}
