apiVersion: linstor.linbit.com/v1alpha1
kind: LinstorControllerSet
metadata:
  name: {{ template "linstor-operator.fullname" . }}-cs
spec:
  etcdURL: etcd://{{ .Release.Name }}-etcd:2379  # TODO: Fix
  drbdRepoCred: {{ .Values.drbdRepoCred }}
  linstorControllerImage: {{ .Values.operator.controllerSet.spec.linstorControllerImage }}
  linstorControllerVersion: {{ .Values.operator.controllerSet.spec.linstorControllerVersion }}