apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: linstorcontrollersets.linstor.linbit.com
spec:
  group: linstor.linbit.com
  names:
    kind: LinstorControllerSet
    listKind: LinstorControllerSetList
    plural: linstorcontrollersets
    singular: linstorcontrollerset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: LinstorControllerSet is the Schema for the linstorcontrollersets
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: LinstorControllerSetSpec defines the desired state of LinstorControllerSet
          properties:
            etcdURL:
              type: string
          required:
          - etcdURL
          type: object
        status:
          description: LinstorControllerSetStatus defines the observed state of LinstorControllerSet
          properties:
            ControllerStatus:
              description: ControllerStatus information.
              properties:
                nodeName:
                  description: The hostname of the kubelet running the node
                  type: string
                registeredOnController:
                  description: Indicates if the node has been created on the controller.
                  type: boolean
              required:
              - nodeName
              - registeredOnController
              type: object
            SatelliteStatuses:
              description: SatelliteStatuses by hostname.
            errors:
              description: Errors remaining that will trigger reconciliations.
              items:
                type: string
              type: array
          required:
          - ControllerStatus
          - SatelliteStatuses
          - errors
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
