apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: linstornodesets.linstor.linbit.com
spec:
  group: linstor.linbit.com
  names:
    kind: LinstorNodeSet
    listKind: LinstorNodeSetList
    plural: linstornodesets
    singular: linstornodeset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: LinstorNodeSet is the Schema for the linstornodesets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: LinstorNodeSetSpec defines the desired state of LinstorNodeSet
          properties:
            disableDRBDKernelModuleInjection:
              description: DisableDRBDKernelModuleInjection turns off automatic injection
                of the DRBD kernel module on the host system when set to true.
              type: boolean
            storagePools:
              description: StoragePools is a list of StoragePools for LinstorNodeSet
                to manage.
              properties:
                lvmPools:
                  description: LVMPools for LinstorNodeSet to manage.
                  items:
                    description: StoragePoolLVM represents LVM storage pool to be
                      managed by a LinstorNodeSet
                    properties:
                      name:
                        description: Name of the storage pool.
                        type: string
                      volumeGroup:
                        description: Name of underlying lvm group
                        type: string
                    required:
                    - name
                    - volumeGroup
                    type: object
                  type: array
                lvmThinPools:
                  description: LVMThinPools for LinstorNodeSet to manage.
                  items:
                    description: StoragePoolLVMThin represents LVM Thin storage pool
                      to be managed by a LinstorNodeSet
                    properties:
                      thinVolume:
                        description: Name of underlying lvm thin volume
                        type: string
                    required:
                    - thinVolume
                    type: object
                  type: array
              required:
              - lvmPools
              - lvmThinPools
              type: object
          required:
          - disableDRBDKernelModuleInjection
          - storagePools
          type: object
        status:
          description: LinstorNodeSetStatus defines the observed state of LinstorNodeSet
          properties:
            SatelliteStatuses:
              description: SatelliteStatuses by hostname.
            errors:
              description: Errors remaining that will trigger reconciliations.
              items:
                type: string
              type: array
          required:
          - SatelliteStatuses
          - errors
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
