---
apiVersion: linstor.linbit.com/v1alpha1
kind: LinstorControllerSet
metadata:
  name: linstor-cs
  # etcdURL url for controller persistence.
  etcdURL: "etcd://linstor-etcd.default.svc.cluster.local:2379"
  # K8s secret for repo credential
  drbdRepoCred: "drbdiocred"
---
apiVersion: linstor.linbit.com/v1alpha1
kind: LinstorNodeSet
metadata:
  name: linstor-ns
spec:
  disableDRBDKernelModuleInjection: false
  
  # K8s secret for repo credential
  drbdRepoCred: "drbdiocred"

  # LINSTOR Satellite image source and tag/version
  linstorSatImage: "drbd.io/linstor-satellite"
  linstorSatVersion: "v1.4.2"

  # StoragePools for the NodeSet to manage.
  storagePools:
    lvmPools:
    - name: "lvm-thick"

      # linstorpool must be an already existing lvm
      # volume group on the kubelet each Linstor
      # node is scheduled on.
      volumeGroup: "drbdpool"
    lvmThinPools:
    - name: "lvm-thin"
      volumeGroup: "drbdpool"

      # linstorthinpool must be an already existing
      # lvm thin volume backed linstorpool on the
      # kubelet each Linstor node is scheduled on.
      thinVolume: "thinpool"
