---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: linstor-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - linstor-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - linstor.linbit.com
  resources:
  - '*'
  - linstorcontrollersets
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linstor-operator
subjects:
- kind: ServiceAccount
  name: linstor-operator
roleRef:
  kind: Role
  name: linstor-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linstor-operator
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: linstorcontrollersets.linstor.linbit.com
spec:
  group: linstor.linbit.com
  names:
    kind: LinstorControllerSet
    listKind: LinstorControllerSetList
    plural: linstorcontrollersets
    singular: linstorcontrollerset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: LinstorControllerSet is the Schema for the linstorcontrollersets
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: LinstorControllerSetSpec defines the desired state of LinstorControllerSet
          properties:
            etcdURL:
              description: EtcdURL is the URL of the ETCD endpoint for LINSTOR Controller
              type: string
            drbdRepoCred:
              description: DrbeRepoCred is the name of the kubernetes secret that
                holds the drbd.io credential
              type: string
            linstorControllerImage:
              description: LinstorControllerImage is the image location for the LINSTOR
                controller/server container
              type: string
            linstorControllerVersion:
              description: LinstorControllerVersion is the image tag/version for the LINSTOR
                controller/server container
              type: string
          required:
          - etcdURL
          - drbdRepoCred
          - linstorControllerImage
          - linstorControllerVersion
          type: object
        status:
          description: LinstorControllerSetStatus defines the observed state of LinstorControllerSet
          properties:
            ControllerStatus:
              description: ControllerStatus information.
              properties:
                nodeName:
                  description: The hostname of the kubelet running the node
                  type: string
                registeredOnController:
                  description: Indicates if the node has been created on the controller.
                  type: boolean
              required:
              - nodeName
              - registeredOnController
              type: object
            SatelliteStatuses:
              description: SatelliteStatuses by hostname.
            errors:
              description: Errors remaining that will trigger reconciliations.
              items:
                type: string
              type: array
          required:
          - ControllerStatus
          - SatelliteStatuses
          - errors
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: linstornodesets.linstor.linbit.com
spec:
  group: linstor.linbit.com
  names:
    kind: LinstorNodeSet
    listKind: LinstorNodeSetList
    plural: linstornodesets
    singular: linstornodeset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: LinstorNodeSet is the Schema for the linstornodesets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: LinstorNodeSetSpec defines the desired state of LinstorNodeSet
          properties:
            drbdKernelModuleInjectionMode:
              description: drbdKernelModuleInjectionMode selects the source for the DRBD kernel module
              type: string
              enum:
              # No module will be injected
              - None
              # The module will be compiled from sources available on the host
              - Compile
              # A module included in the injector image will be used
              - ShippedModules
            storagePools:
              description: StoragePools is a list of StoragePools for LinstorNodeSet
                to manage.
              properties:
                lvmPools:
                  description: LVMPools for LinstorNodeSet to manage.
                  items:
                    description: StoragePoolLVM represents LVM storage pool to be
                      managed by a LinstorNodeSet
                    properties:
                      name:
                        description: Name of the storage pool.
                        type: string
                      volumeGroup:
                        description: Name of underlying lvm group
                        type: string
                    required:
                    - name
                    - volumeGroup
                    type: object
                  type: array
                lvmThinPools:
                  description: LVMThinPools for LinstorNodeSet to manage.
                  items:
                    description: StoragePoolLVMThin represents LVM Thin storage pool
                      to be managed by a LinstorNodeSet
                    properties:
                      thinVolume:
                        description: Name of underlying lvm thin volume
                        type: string
                    required:
                    - thinVolume
                    type: object
                  type: array
              required:
              - lvmPools
              - lvmThinPools
              type: object
            drbdRepoCred:
              description: DrbeRepoCred is the name of the kubernetes secret that
                holds the drbd.io credential
              type: string
            linstorSatImage:
              description: LinstorSatImage is the image location for the LINSTOR
                satellite container
              type: string
            linstorSatVersion:
              description: LinstorSatVersion is the image tag/version for the LINSTOR
                satellite container
              type: string
            linstorKernelModImage:
              description: LinstorKernelModImage is the image location for the LINSTOR/
                DRBD kernel module injector container
              type: string
            linstorKernelModVersion:
              description: LinstorKernelModVersion is the image tag/version for the LINSTOR/
                DRBD kernel module injector container
              type: string
          required:
          - drbdKernelModuleInjectionMode
          - storagePools
          - drbdRepoCred
          - linstorSatImage
          - linstorSatVersion
          - linstorKernelModImage
          - linstorKernelModVersion
          type: object
        status:
          description: LinstorNodeSetStatus defines the observed state of LinstorNodeSet
          properties:
            SatelliteStatuses:
              description: SatelliteStatuses by hostname.
            errors:
              description: Errors remaining that will trigger reconciliations.
              items:
                type: string
              type: array
          required:
          - SatelliteStatuses
          - errors
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: scheduling.k8s.io/v1 # v1beta1 for 1.13
kind: PriorityClass
metadata:
  name: "linstor-cs-priority-class"
value: 1000010
globalDefault: false
description: "Priority class for linstor controller"
---
apiVersion: scheduling.k8s.io/v1 # v1beta1 for 1.13
kind: PriorityClass
metadata:
  name: "linstor-ns-priority-class"
value: 1000000
globalDefault: false
description: "Priority class for linstor satellite(s)"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linstor-operator
  labels:
    name: linstor-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: linstor-operator
  template:
    metadata:
      labels:
        name: linstor-operator
    spec:
      serviceAccountName: linstor-operator
      containers:
        - name: linstor-operator
          image: "drbd.io/linstor-operator:v0.1.3"
          command:
          - linstor-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "linstor-operator"
      imagePullSecrets:
      - name: drbdiocred
---
